[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps =
  adafruit/DHT sensor library @ ^1.4.6
  adafruit/Adafruit Unified Sensor @ ^1.1.15
  knolleary/PubSubClient @ ^2.8
  milesburton/DallasTemperature @ ^4.0.4
  paulstoffregen/OneWire @ ^2.3.8
lib_ldf_mode = chain+
build_flags =
  -DCORE_DEBUG_LEVEL=3
